### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by sasso** [checkr/codeflow#44]
In Codeflow dashboard switch to another environment that keeps track of its own features, services, releases and has its own settings. Used for `staging` and `development` environment and with combination of issue #27 we could use it to deploy and test PR's

**Comment by kylegato** [comment]
Activity

**Comment by sasso** [comment]
@kylegato we are working on a new version that will include support for multiple environments and some other features -> https://github.com/codeamp/circuit 

Codeflow is still supported and used in production but we are planning to roll out CodeAmp to production in the following weeks.
